language: cpp


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - lcov

matrix:
  include:
    - name: "linux-x86_64-gcc"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - INIT_DIRS="chmod +x build_deps.sh "
        - BUILD_THIRD_LIB="./build_deps.sh All"
        - BUILD_YLIB="mkdir -p build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux_x64_gcc.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/install -DBUILD_YLIB_ARCH=x86_64 .. && make && make install"
        - YLIB_RUN_TEST=""

    # - name: "linux-x86_64-clang"
    #   os: linux
    #   dist: bionic
    #   compiler:
    #     - clang
    #     - gcc
    #   env:
    #     - INIT_DIRS="chmod +x build_deps.sh "
    #     - BUILD_THIRD_LIB="./build_deps.sh All"
    #     - BUILD_YLIB="mkdir -p build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux_x64_clang.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/install -DBUILD_YLIB_ARCH=x86_64 .. && make && make install"
    #     - YLIB_RUN_TEST=""

    - name: "windows-vs2017"
      os: windows
      dist: 1803-containers
      env:
        - INIT_DIRS=""
        - BUILD_THIRD_LIB=".\build_deps.bat vs2017 x86_64"
        - BUILD_YLIB="mkdir build && cmake -T v141,host=x64 -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_YLIB_ARCH=x86_64 .. && cmake --build . --config Release --target install   "
        - YLIB_RUN_TEST=""

    - name: "linux-arm64-gcc"
      os: linux
      arch: arm64
      dist: bionic
      compiler: gcc
      env:
        - INIT_DIRS=""
        - BUILD_THIRD_LIB=""
        - BUILD_YLIB=""
        - YLIB_RUN_TEST=""

    - name: "linux-arm64-clang"
      os: linux
      arch: arm64
      dist: bionic
      compiler: clang
      env:
        - INIT_DIRS=""
        - BUILD_THIRD_LIB=""
        - BUILD_YLIB=""
        - YLIB_RUN_TEST=""

    - name: "linux-arm32-gcc"
      os: linux
      arch: arm64
      dist: bionic
      env:
        - INIT_DIRS=""
        - BUILD_THIRD_LIB=""
        - BUILD_YLIB=""
        - YLIB_RUN_TEST=""

    - name: "linux-x86_64-gcc_CodeCoverage"
      os: linux
      dist: xenial
      compiler: gcc
      env:
        - INIT_DIRS="chmod +x build_deps.sh "
        - BUILD_THIRD_LIB="./build_deps.sh All"
        - BUILD_YLIB="mkdir -p build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux_x64_gcc.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/install -DBUILD_YLIB_ARCH=x86_64 -DENABLE_YLIB_COVERAGE=ON .. && make && make install"
        - YLIB_RUN_TEST="cd install/tests && ./scripts_for_all_tests.sh"
        - PROCESS_COVERAGE_FILE="cd ../.. && lcov -d ./src -c -o lcov.info && lcov -r lcov.info '/usr/*' '*/include/third_part/*' -o lcov.info && bash <(curl -s https://codecov.io/bash) -f lcov.info"

before_install:
  - eval "${INIT_DIRS}"
  - eval "${BUILD_THIRD_LIB}"
  - eval "${BEFORE_BUILD_YLIB}"

script:
  - eval "${BUILD_YLIB}"
  - eval "${YLIB_RUN_TEST}"
  - eval "${PROCESS_COVERAGE_FILE}"
