name: android_32bit
on: [push, pull_request]

jobs:
  build_android_armeabi:
    name: build on 32bit(last_ubuntu) platefrom using clang
    runs-on: ubuntu-latest
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2

    - name: build ylib
      working-directory: /home/runner/work/yLib/yLib/build
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE="${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake" -DANDROID_ABI="armeabi-v7a" -DANDROID_PLATFORM=android-21 -DCMAKE_BUILD_TYPE=Release -DBUILD_YLIB_ARCH=android ..
        make -j`nproc`
        make install
