name: linux_x86_clang
on: [push, pull_request]

jobs:
  build_last_ubuntu_x86_clang:
    name: build on x86(last_ubuntu) platefrom  using clang
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2

    - name: set env and init
      env:
        THIRD_PART_PATH_ROOT: /home/runner/work/yLib/yLib/third_part
      run: |
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        chmod +x build_deps.sh
        mkdir -p build
        
      working-directory: /home/runner/work/yLib/yLib
      
    - name: update
      run: sudo apt-get update

    - name: install gcc multilib
      run: sudo apt-get install gcc-multilib g++-multilib

    - name: build third part
      env:
        THIRD_PART_PATH_ROOT: /home/runner/work/yLib/yLib/third_part
      run: |
        cd $GITHUB_WORKSPACE
        ./build_deps.sh All  x86 linux

      working-directory: /home/runner/work/yLib/yLib

    - name: build ylib
      working-directory: /home/runner/work/yLib/yLib/build
      env:
        CC: clang
        CXX: clang++
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux_x64_clang_m32.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/install -DBUILD_YLIB_ARCH=x86 ..
        make
        make install

    - name: test ylib
      working-directory: /home/runner/work/yLib/yLib/build
      run: |
        cd install/tests
        ./scripts_for_tests.sh