name: ubuntu1804_aarch64_gcc
on: [push, pull_request]


jobs:
  build_linux_aarch64:
    name: build on aarch64(last_ubuntu) platefrom  using gcc
    runs-on: ubuntu-18.04
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2

    - name: set env and init
      env:
        THIRD_PART_PATH_ROOT: /home/runner/work/yLib/yLib/third_part
      run: |
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        chmod +x build_deps.sh
        mkdir -p build
        
      working-directory: /home/runner/work/yLib/yLib

    - name: cache-qemu
      id: cache-qemu
      uses: actions/cache@v1
      with:
        path: qemu-install
        key: qemu-arm-install-cache-key

    - name: checkout-qemu
      #if we don't hit cache-qemu, we should compile qemu
      if: steps.cache-qemu.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: qemu/qemu
        path: qemu
        #v5.2.0
        ref: 553032db17440f8de011390e5a1cfddd13751b0b
    - name: qemu
      if: steps.cache-qemu.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install ninja-build
        cd qemu
        mkdir build
        cd build

        ../configure --prefix=`pwd`/install --target-list=aarch64-linux-user --disable-system
        make -j2
        make install
        cp -r aarch64-linux-user/qemu-aarch64 $GITHUB_WORKSPACE/qemu-install

    - name: arm-gnu-toolchain
      run: |
        sudo apt-get update
        sudo apt-get install g++-aarch64-linux-gnu   

    - name: build third part
      env:
        THIRD_PART_PATH_ROOT: /home/runner/work/yLib/yLib/third_part
      run: |
        cd $GITHUB_WORKSPACE
        ./build_deps.sh All aarch64 linux

      working-directory: /home/runner/work/yLib/yLib           

    - name: build ylib
      working-directory: /home/runner/work/yLib/yLib/build
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/linux_aarch64_gcc.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/install -DBUILD_YLIB_ARCH=aarch64 ..
        make
        make install

    # - name: test ylib
    #   working-directory: /home/runner/work/yLib/yLib/build
    #   run: |
    #     export PATH=$GITHUB_WORKSPACE/qemu-install/bin:$PATH
    #     cd install/tests
    #     ./scripts_for_tests.sh qemu-aarch64

  build_linux_arm82:
    name: build on arm82(last_ubuntu) platefrom  using gcc
    runs-on: ubuntu-18.04
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2