name: windows_x86_vs2015
on: [push, pull_request]

jobs:
  build_windows_x86_vs2017:
    name: build on x86(windows) platefrom  using vs2015
    runs-on: windows-latest
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2

    - name: set env and init
      env:
        THIRD_PART_PATH_ROOT: D:\a\yLib\yLib\third_part
      run: |
        echo $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        mkdir build_vs2015_x86
        ls $GITHUB_WORKSPACE

    - name: build third part
      env:
        THIRD_PART_PATH_ROOT: D:\a\yLib\yLib\third_part
      run: |
        cd $GITHUB_WORKSPACE
        build_deps.bat vs2015 x86

      working-directory: $GITHUB_WORKSPACE

    - name: build ylib
      working-directory: D:\a\yLib\yLib\
      run: |
        cd $GITHUB_WORKSPACE\build_vs2015_x86
        cmake -T v140,host=x64 -A Win32 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DBUILD_YLIB_ARCH=x86_64 ..
        cmake --build . --config Release --target install      