name: windows_x64_vs2019
on: [push, pull_request]

jobs:
  build_windows_x64_vs2019:
    name: build on x64(windows) platefrom  using vs2019
    runs-on: windows-latest
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2