name: windows_x64_vs2017
on: [push, pull_request]

jobs:
  build_windows_x64_vs2017:
    name: build on x64(windows) platefrom  using vs2017
    runs-on: windows-latest
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2

    - name: set env and init
      env:
        THIRD_PART_PATH_ROOT: /home/runner/work/yLib/yLib/third_part
      run: |
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        mkdir build_vs2017_x64

    - name: build third part
      env:
        THIRD_PART_PATH_ROOT: /home/runner/work/yLib/yLib/third_part
      run: |
        cd $GITHUB_WORKSPACE
        build_deps.bat vs2017 x86_64 

      working-directory: $GITHUB_WORKSPACE

    - name: build ylib
      working-directory: /home/runner/work/yLib/yLib/build
      run: |
        cd $GITHUB_WORKSPACE\build_vs2017_x64
        cmake -T v141,host=x64 -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DBUILD_YLIB_ARCH=x86_64 ..
        cmake --build . --config Release --target install     