name: windows_x86_vs2017
on: [push, pull_request]

jobs:
  build_windows_x86_vs2017:
    name: build on x86(windows) platefrom  using vs2017
    runs-on: windows-latest
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2

    - name: set env and init
      env:
        THIRD_PART_PATH_ROOT: D:\a\yLib\yLib\third_part
      run: |
        $download_ps_file = "${{github.workspace}}/download_third_part.ps1"
        cd third_part
        powershell $download_ps_file
        cd ..
        mkdir build_vs2017_x86

    - name: build third part
      env:
        THIRD_PART_PATH_ROOT: D:\a\yLib\yLib\third_part
      run: |
        .\build_deps.bat vs2017 x86

      working-directory: D:\a\yLib\yLib\

    - name: build ylib
      working-directory: D:\a\yLib\yLib\
      run: |
        cd build_vs2017_x86
        cmake -T v141,host=x64 -A Win32 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=install -DBUILD_YLIB_ARCH=x86 ..
        cmake --build . --config Release --target install      