name: windows_x64_vs2015
on: [push, pull_request]

jobs:
  build_windows_x64_vs2015:
    name: build on x64(windows) platefrom  using vs2015
    runs-on: windows-latest
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2
    
    - name: set env and init
      env:
        THIRD_PART_PATH_ROOT: D:\a\yLib\yLib\third_part
      run: |
        Invoke-WebRequest -Uri http://www.interlog.com/~tcharron/wgetwin-1_5_3_1-binary.zip -OutFile wgetwin-1_5_3_1-binary.zip
        7z x ./wgetwin-1_5_3_1-binary.zip
        mkdir build_vs2015_x64
        ls 

    - name: build third part
      env:
        THIRD_PART_PATH_ROOT: D:\a\yLib\yLib\third_part
      run: |
        set PATH=%PATH%;%cd%
        .\build_deps.bat vs2015 x86_64 

      working-directory: D:\a\yLib\yLib\

    - name: build ylib
      working-directory: D:\a\yLib\yLib\
      run: |
        cd build_vs2015_x64
        cmake -T v140,host=x64 -A x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DBUILD_YLIB_ARCH=x86_64 ..
        cmake --build . --config Release --target install       