name: windows_x86_vs2019
on: [push, pull_request]

jobs:
  build_windows_x86_vs2019:
    name: build on x86(windows) platefrom  using vs2019
    runs-on: windows-latest
    steps:
    - name: checkout my rep
      uses: actions/checkout@v2

    - name: set env and init
      env:
        THIRD_PART_PATH_ROOT: D:\a\yLib\yLib\third_part
      run: |
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE
        cd $GITHUB_WORKSPACE
        mkdir build_vs2019_x86

    - name: build third part
      env:
        THIRD_PART_PATH_ROOT: D:\a\yLib\yLib\third_part
      run: |
        cd $GITHUB_WORKSPACE
        build_deps.bat vs2019 x86

      working-directory: $GITHUB_WORKSPACE

    - name: build ylib
      working-directory: D:\a\yLib\yLib\
      run: |
        cd $GITHUB_WORKSPACE\build_vs2019_x86
        cmake -T v141,host=x64 -A Win32 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%cd%/install -DBUILD_YLIB_ARCH=x86_64 ..
        cmake --build . --config Release --target install      